<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Page Include="..\DashboardView.xaml" />
    <Compile Include="..\DashboardView.xaml.cs" />
    <Page Include="..\ImportView.xaml" />
    <Compile Include="..\ImportView.xaml.cs" />
    <Page Include="..\ProcessorView.xaml" />
    <Compile Include="..\ProcessorView.xaml.cs" />
  </ItemGroup>

</Project>
